### ISSUE TITLE
BuildRun fails and reports: /bin/bash: line 26: /platform/env/target/quarkus-app/*.jar: No such file or directory

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/testing#7]
## Issue

BuildRun fails and reports as error:
```
> Processing environment variables...                                                                                                                                                │
/bin/bash: line 26: /platform/env/target/quarkus-app/*.jar: No such file or directory
```
when we use as Task definition: https://github.com/redhat-buildpacks/testing/blob/main/k8s/shipwright/secured/clusterbuildstrategy.yml

**Comment by BarDweller** [comment]
Seeing your comment in slack may have provided further info.. 

`-DBP_MAVEN_BUILT_ARTIFACT="target/quarkus-app/lib/ target/quarkus-app/*.jar target/quarkus-app/app/ target/quarkus-app/quarkus/" \`

I'm guessing this is in the env, which makes me suspect that the loop that's processing those env vars isn't handling spaces in the env value well.. try testing that loop locally with variations of that env var (with or without enclosing double or single quotes etc).. suspect it will fail and at somepoint end up treating the values after the spaces as if they were additional env keys, which leads the inevitable failure when it attempts to use the key as part of a filename.

**Comment by cmoulliard** [comment]
Fixed with new BuildStrategy.yml definition
